name: Workflow dispatch inputs and security verification

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        description: Input your message

      lang-selector:
        type: choice
        description: Choose your language
        options:
          - English
          - Norsk

jobs:
  hello-english-job:
    runs-on: ubuntu-latest
    if: inputs.lang-selector == 'English'
    name: Hello ${{ inputs.message }} 🇬🇧"

  hello-norsk-job:
    runs-on: ubuntu-latest
    if: inputs.lang-selector == 'Norsk'
    name: Hei ${{ inputs.message }} 🇳🇴"
