name: Workflow dispatch inputs and security verification

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        description: Input your message

      lang-selector:
        type: choice
        description: Choose your language
        options:
          - English
          - Norsk

jobs:
  hello-english-job:
    runs-on: ubuntu-latest
    if: inputs.lang-selector == 'English'
    steps:
      - name: Print message to terminal
        run: echo "Hello ${MESSAGE}!"
        env:
          MESSAGE: ${{ inputs.message }} 

  hello-norsk-job:
    runs-on: ubuntu-latest
    if: inputs.lang-selector == 'Norsk'
    steps:
      - name: Print message to terminal
        run: echo "Hei ${MESSAGE}!"
        env:
          MESSAGE: ${{ inputs.message }}
